package com.ledgerbloom.error;

public enum ErrorCode {
	CATEGORY_NOT_FOUND,
	CATEGORY_NAME_ALREADY_EXISTS,
	CATEGORY_IN_USE,
	EXPENSE_NOT_FOUND,
	INVALID_EXPENSE_DATA,
	VALIDATION_FAILED,
	INVALID_REQUEST,
	INTERNAL_SERVER_ERROR
}
