package com.ledgerbloom.error;

public enum ErrorCode {
	CATEGORY_NOT_FOUND,
	CATEGORY_NAME_ALREADY_EXISTS,
	CATEGORY_IN_USE,
	EXPENSE_NOT_FOUND,
	INVALID_EXPENSE_DATA,
	INCOME_ENTRY_NOT_FOUND,
	INVALID_INCOME_DATA,
	BUDGET_NOT_FOUND,
	BUDGET_ALREADY_EXISTS,
	CATEGORY_BUDGET_LIMIT_NOT_FOUND,
	CATEGORY_BUDGET_ALREADY_EXISTS,
	INVALID_BUDGET_DATA,
	VALIDATION_FAILED,
	INVALID_REQUEST,
	INTERNAL_SERVER_ERROR
}
